### ISSUE TITLE
Add event for key input (for empty input validation)

### ISSUE THREAD

**Issue by helmerdavila** [olefirenko/vue-google-autocomplete#12]
Can i add and send a merge request?

**Comment by olefirenko** [comment]
I have just added more events (including `change` and `keypress` events) which are triggered from the component and updated docs. Please check it https://github.com/olefirenko/vue-google-autocomplete/commit/6c9bc2d23f1bf4836ae7588a6a87c865f90c7e55 . Is it what you need?

**Comment by helmerdavila** [comment]
Thank you. I wrote similar functions but on my files project.
