### ISSUE TITLE
How to use in typescript

### ISSUE THREAD

**Issue by MKBLR23** [olefirenko/vue-google-autocomplete#129]
Error:(5, 35) TS2307: Cannot find module 'vue-google-autocomplete'. install @tyeps/vue-google-autocomplete as dev dependency.

**Comment by on3dd** [comment]
Have you solved this problem?

**Comment by MKBLR23** [comment]
Yes @on3dd, using declare module 'vue-google-autocomplete';

**Comment by shubham-dianapps** [comment]
> Yes @on3dd, using declare module 'vue-google-autocomplete';

@MKBLR23 can you help me, how did you solve it?

**Comment by MKBLR23** [comment]
![image](https://user-images.githubusercontent.com/10767988/104682567-008e6e80-571b-11eb-9437-7e86065acc8f.png)

I have create one .d.ts file for this and declare the module. Please follow the screen shot I have shared.

**Comment by shubham-dianapps** [comment]
I did that, but then I was getting the following error -> @typescript-eslint/no-unsafe-assignment
for now, I Have updated the eslint rules, but did you also faced the same?
