### ISSUE TITLE
Como puedo hacer para que se muestre en Ventanas modales

### ISSUE THREAD

**Issue by david17art** [olefirenko/vue-google-autocomplete#13]
Lo usé en una ventana modal, y no me funciono, los resultados se muestran es abajo

**Comment by olefirenko** [comment]
Could you please use English :-). As I understood through Google Translate you have some issues with modals. Please give more info about the issue.

**Comment by helmerdavila** [comment]
@david17art Lo usé en un modal y me funcionó perfectamente. El modal nada más tiene que estar pre-cargado en tu componente
