### ISSUE TITLE
IOS Problem

### ISSUE THREAD

**Issue by Diferno** [olefirenko/vue-google-autocomplete#14]
Hi!  I just stepped on a problem with iPhones. You start typing, the autocomplete works fine suggesting resutls, but it's impossible to select one of the given options of the dropdown list.
When you click on them, the focus is set on the input again.

Thx in advance!

**Comment by bemyguestdmitriy** [comment]
Could you please provide an URL if possible.
I have just tried on iPhone 7 and SE demo page https://olefirenko.github.io/vue-google-autocomplete/ - all works fine. And there are should not be any issues at all, because basically this component just wrapper on top of Google Places API.

**Comment by Diferno** [comment]
Hi, sorry for taking so long. But I've been continuing with development and wanted be sure it was still beeing an issue.
Tryed your demo on an iPhone 7, works OK, but when using it on my page, the drop down list kind of floats away and doesn't allow selection :(
It's on the 2nd step of the wizard at [alarmios.com](http://alarmios.com) .

FYI, I'm using quasar framework with the material design layout. On Macbook works ok, so maybe it's an iPhone tapping problem.

**Comment by Diferno** [comment]
After smashing my head, the issue was with the Fastclick library 
[https://github.com/ftlabs/fastclick/pull/347](https://github.com/ftlabs/fastclick/pull/347)

Solved it with @collegeman solution

Thanks for the support ;)
