### ISSUE TITLE
Pass API key to component ?

### ISSUE THREAD

**Issue by tlloydukdev** [olefirenko/vue-google-autocomplete#143]
I like what you've done here,
Is there a way to pass the API key to the component rather than include the script in the wrapper index.html ?

**Comment by tlloydukdev** [comment]
I was already using vue2-google-maps and so it was conflicting, but all I had to do was pass the libraries property to the load option on VueGoogleMaps and then both libraries share the same google object

**Comment by chemeng** [comment]
How did you make this work? Do you register the autocomplete component after the google maps one? I'm getting a `google is not defined` error.

**Comment by evanlegamer** [comment]
No answer ?
