### ISSUE TITLE
Fields option not working

### ISSUE THREAD

**Issue by jongbonga** [olefirenko/vue-google-autocomplete#147]
the new fields option isn't working as per the description.

```
data() {
    return {
      fieldOptions: ["formatted_address", "id", "name", "vicinity"]
    };
  }
```

```
<vue-google-autocomplete
        id="start"
        v-model="start.text"
        country="zaf"
        :fields="fieldOptions"
        @placechanged="getAddress"
        placeholder="Start typing"
></vue-google-autocomplete>
```

<img width="448" alt="Screenshot 2021-02-25 at 12 05 10" src="https://user-images.githubusercontent.com/12111716/109137334-c2e12480-7761-11eb-8729-faaaa2b90c38.png">

**Comment by olefirenko** [comment]
@jongbonga Please try now. I just pushed new [1.1.1](https://www.npmjs.com/package/vue-google-autocomplete/v/1.1.1) release to npm. Sorry about the delay.

**Comment by jongbonga** [comment]
Hi @olefirenko no need to apologize!

Thank you for your time ❤️
