### ISSUE TITLE
Version of Vue

### ISSUE THREAD

**Issue by Fleeck** [olefirenko/vue-google-autocomplete#2]
Hello, which Vue.js version do you support? Not working with Vue 2.2.1

**Comment by Fleeck** [comment]
![image](https://cloud.githubusercontent.com/assets/12518334/23406560/3523940a-fdc8-11e6-848b-5177a3e55178.png)

I am loading maps API and encounter such errors. Probably that's because google maps hasn't loaded at the moment.

**Comment by olefirenko** [comment]
Hello!
Have you included in `<head>` section load of the Google Places API
```
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY_HERE&libraries=places"></script>
```
It seems that you have not. Let me know.
Thanks.
