### ISSUE TITLE
default value

### ISSUE THREAD

**Issue by azar-maghsoodi** [olefirenko/vue-google-autocomplete#23]
Hello guys
Is there any way to define a default address or not?

**Comment by julienr-geronimo** [comment]
Hi @azar-maghsoodi 

On my side when i mount the component is set :value=search with a defaultAddress (but i don't search for it with vue-google-autocomplete) 

Don't know if it's helping :neutral_face:

**Comment by azar-maghsoodi** [comment]
Hi @julienr-geronimo 
thank you for answer me.
it helps alot
