### ISSUE TITLE
Question: How to set API key for npm or yarn installations?

### ISSUE THREAD

**Issue by tandasima** [olefirenko/vue-google-autocomplete#27]
How do I set the API key if installed via npm like in the example?

Thanks

**Comment by tandasima** [comment]
Nevermind I figured it out. 

Thanks.

**Comment by LukeXF** [comment]
How did you set it? I'm having the same problem.

**Comment by AverageCakeSlice** [comment]
https://preview.redd.it/7khgt29lp1121.jpg?width=853&auto=webp&s=8e6260028a09e868a282f116789c9e44bf52f5c1
