### ISSUE TITLE
Types parameter doesn't work

### ISSUE THREAD

**Issue by akapit** [olefirenko/vue-google-autocomplete#32]
I'm not able to make the component bring only cities or localities.
The documentation says I can pass types parameter but It doesn't work.

Even If I pass 'address' which is the default it doesn't work; it forces me to take out the parameter.

How can I make it bring only cities/ localities?

Thanks a lot

**Comment by olefirenko** [comment]
Below an example (probably you forgot brackets):
```
            <vue-google-autocomplete
                id="map2"
                ref="toAddress"
                classname="form-control"
                placeholder="Start typing"
                v-on:placechanged="getToData"
                types="(cities)"
                country="us"
            >
            </vue-google-autocomplete>
```

The result https://monosnap.com/file/7LzQoqI84t437tly7Cq0MSbB53gkWw

**Comment by AlboVieira** [comment]
@olefirenko it solves the problem, maybe we should add it to readme.

**Comment by hovsep** [comment]
@olefirenko Thank you!
I added brackets to types param value and it works!

**Comment by mgibowski** [comment]
I also lost some time before coming here and trying the `types="(cities)"`.

I agree that it would be valuable if the README contained this example.

**Comment by toddpadwick** [comment]
How do you enter multiple types? Should the brackets be wrapped around all of them? or each individually?
For example, I need the following – but this doesn't seem to work yet returns no errors:
`types="address,(cities),postal_code,locality"`

Shouldn't this be of type array?

**Comment by chandlerwilcox88** [comment]
> How do you enter multiple types? Should the brackets be wrapped around all of them? or each individually? For example, I need the following – but this doesn't seem to work yet returns no errors: `types="address,(cities),postal_code,locality"`
> 
> Shouldn't this be of type array?

I used this and it works but it shows a vue warn error:

`:types="([address,cities,sublocality,postal_code,country])"`

**Comment by topongo** [comment]
> ...but it shows a vue warn error

probably the type of the prop "types" must be changed
