### ISSUE TITLE
How to 

### ISSUE THREAD

**Issue by lmatab** [olefirenko/vue-google-autocomplete#33]
Hello, thanks for this great component.

I am being able already to make it work, and it is like a charm!

I am now trying to pass a value when I edit the record and I would like to populate this field, I guess it is using  the ' autocompleteText '  data. I tried to  set  v-model="updatedvaluenew" and get the variable using  the computed variable but still no luck, any thoughts?

Thanks

**Comment by olefirenko** [comment]
Is it resolved by this PR https://github.com/olefirenko/vue-google-autocomplete/pull/34 ?
