### ISSUE TITLE
How to prevent enter action after choosing address?

### ISSUE THREAD

**Issue by koddr** [olefirenko/vue-google-autocomplete#38]
Hello.

I have a form on my site (Django + Vue.js frontend) where I'm using your awesome vue plugin. But if I click enter key (on keyboard) for choosing address (in Google drop-down menu) – form is submitting :(

I try to add to `<vue-google-autocomplete ...>` tag this attribute: `@keydown.enter.prevent` but it's not working. Help me, please.

**Comment by Konafets** [comment]
I added `@keydown.enter.prevent=""` to my form to make this work.

**Comment by kashifullahwebdeveloper** [comment]
I tried to add `@keypress.enter.prevent=""` attribute in `<vue-google-autocomplete ...>`
and worked for me :)

Is it the correct way?

**Comment by koddr** [comment]
@kashifullahwebdeveloper if it's work, why not?! :)

**Comment by toddpadwick** [comment]
None of the above solutions worked for me. Any other workaround?
