### ISSUE TITLE
ReferenceError: google is not defined on Production

### ISSUE THREAD

**Issue by BenjaminRosell** [olefirenko/vue-google-autocomplete#39]
Hello there ! 

First : Thanks so much for this component, it's awesome :)

I am running into a small problem. Everything works great on development, but when I run npm run dev, and start using in production, I get the following error : 

vue.esm.js:523 ReferenceError: google is not defined

Any ideas on what could be going wrong ?

**Comment by olefirenko** [comment]
Have you added to <head> section this:
```
<head>
    …
    <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY_HERE&libraries=places"></script>
  </head>
```

**Comment by BenjaminRosell** [comment]
Now, I feel stupid ! 

Haha :)

Thanks man !

**Comment by kashifullahwebdeveloper** [comment]
Hi @olefirenko, Thank you for amazing component.

I am getting the same error if I include the script in head, because I am using one more plugin for for Google heatmap, link as follow: https://github.com/xkjyeah/vue-google-maps, thus my app giving me this error:  **You have included the Google Maps API multiple times on this page. This may cause unexpected errors.**

Could you please tell me what should I do?

**Comment by LukeXF** [comment]
> Hi @olefirenko, Thank you for amazing component.
> 
> I am getting the same error if I include the script in head, because I am using one more plugin for for Google heatmap, link as follow: https://github.com/xkjyeah/vue-google-maps, thus my app giving me this error: **You have included the Google Maps API multiple times on this page. This may cause unexpected errors.**
> 
> Could you please tell me what should I do?

I'm having the same issue, any support to use an API key through yarn/npm install?

**Comment by auriga1** [comment]
Hi,
this is a possible solution:

install google library with npm:

`npm i @googlemaps/js-api-loader`

then, in your code:

```
import { Loader } from "@googlemaps/js-api-loader";

const loader = new Loader({
    apiKey: 'your key',
    version: 'weekly',
    libraries: ['places']
});
loader.load().then( () => {
});
```

after that loader param is loaded you can use vue-google-autocomplete
