### ISSUE TITLE
Limit search for only one city?

### ISSUE THREAD

**Issue by koddr** [olefirenko/vue-google-autocomplete#40]
Hello. Thanks for your plugin!

Question is how to limit autocomplete search for one city?
For example, how to get addresses only for `USA` (country) and `New York` (city)?

I think, you may add option to plugin like `city` and send string from this option as start prefix in query for Google Maps API.

```html
<vue-google-autocomplete
   ...
   types="address"
   city="New York"
   ...
>
</vue-google-autocomplete>
```

It's will be very helpful 👍

**Comment by Kreshnik** [comment]
Indeed something like mentioned above, would be really helpful.

**Comment by hovsep** [comment]
Please keep in mind that "(cities)" or "(regions)" are collections and must be wrapped with brackets

**Comment by bryster** [comment]
Hey, I'm having a little trouble with the plugin. I'm trying to limit the search to Auckland, New Zealand.
The country part is working but I'm not sure how to use "types" to only allow Auckland addresses

Right now I have:

`
types="(cities)"
country="nz"
`
is the word cities inside of types meant to be a variable inside my components data?
Where do I target Auckland specifically?

Thanks
