### ISSUE TITLE
How to insert address to vue-google-autocomplete field by click button?

### ISSUE THREAD

**Issue by koddr** [olefirenko/vue-google-autocomplete#42]
Hello. I try to make hybrid search address system: classic autocomplete and many buttons with pre-bind addresses. So, how to insert bind address to `vue-google-autocomplete` field by click button?

On my template:

```html
<vue-google-autocomplete ref="address" ... ></vue-google-autocomplete>
<button v-on:click="swapAddress('New York, USA')">New York, USA</button>
```

And js:

```javascript
...
methods: {
    swapAddress: function (location) {
        this.$refs.address = location;
    },
}
...
```

But it doesn't work. Please help me.

**Comment by koresar** [comment]
I assume you need to use `.update()` [method](https://github.com/olefirenko/vue-google-autocomplete#updatevalue).
```
this.$refs.address.update(location)
```

**Comment by koresar** [comment]
Ok. I reproduced your problem. Likely, you just need to wait Vue to render previous (this component's) changes before making your own:
```js
        this.$nextTick(() => { // or Vue.nextTick()
          this.$refs.address.update(location)
        })
```
