### ISSUE TITLE
Clear autocompleteText

### ISSUE THREAD

**Issue by Konafets** [olefirenko/vue-google-autocomplete#43]
Hi, 
 
I like to clear the `autocompleteText` and found that this should be able through the `clear()` method, but I don't get how to use it. Can you give me a hint?

**Comment by olefirenko** [comment]
Hi,

please see the last example in the docs. There is an example of `focus` method.
You should use `refs` and `clear()` method should be called like this (`address` is ref name):
```html
this.$refs.address.clear();
```
