### ISSUE TITLE
Refresh the country filter

### ISSUE THREAD

**Issue by iec989** [olefirenko/vue-google-autocomplete#47]
I have the country attribute pointing to my model: :country="form.step1.contact.country.toLowerCase()"

form.step1.contact.country.toLowerCase() change the value based on a dropdown.

Based in the Vue debugger, form.step1.contact.country.toLowerCase() value is correct, for instance 'es' - however the filter seems to be working only on load time, no if you modify it afterwards.

Any ideas?

**Comment by juanvillegas** [comment]
The country value is ready when the plugin is mounted, and then used to create the Google Autocomplete component. Any changes to the model after this are not watched by the plugin.

If you are up to submitting a PR, this is what you have to do:
1) Add a watcher to the country prop in the VueGoogleAutocomplete component
2) When the watcher is executed, call the _setComponentRestrictions_ function on Autocomplete plugin (https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-multiple-countries)

**Comment by Eoksni** [comment]
@juanvillegas the actual code to fix this issue turned out to be smaller than your comment explaining how to do it :)

**Comment by juanvillegas** [comment]
@Eoksni meant to say I should've just written it? If I were to write it, I would need to write/execute all the tests, go through the whole code to see if there were any other implications, etc. Not that simple right? ;)

**Comment by juanvillegas** [comment]
@Eoksni But good work there!
