### ISSUE TITLE
InvalidValueError: not an instance of HTMLInputElement

### ISSUE THREAD

**Issue by DiogoAbdalla** [olefirenko/vue-google-autocomplete#55]
Im getting the error above in a component where in using VueGoogleAutocomplete

The code is pretty simple: 
`vue-google-autocomplete(id="gaddress2222", placeholder="Endereço", v-on:placechanged="test", v-on:no-results-found="test")`

I am importing the component too 
`components: { QModal, QField, QInput, QSelect, QPopover, QBtn, QAutocomplete, QIcon, QSearch, QDatetime, VueGoogleAutocomplete},`

And I have the gmaps API script on my index.html

So I cant understand what's wrong, seems link a bug

I even have vue-google-autocomplete working perfectly in this same project, in another component, with the same code 

edit: testing more, the problem seems intermittent: sometimes I just wont get the error, and the component will work normally

**Comment by DiogoAbdalla** [comment]
Ok, Ive found a dumb workaround

First I put a v-if on the vuw-google-autocomplete parent container:

`						fieldset(v-if="ready")
							label Endereço:
							vue-google-autocomplete(id="gaddress", placeholder="Endereço", v-on:placechanged="setAddressData")`

ready starts false

Then:
`	mounted(){
		const _this = this;
		setTimeout(function(){
			_this.ready = true;//adasd
		}, 1000)
	},`

And it always works, I never get the error. Seems like an issue with the component trying to initialize too ealry

**Comment by Kambe11** [comment]
.pac-container {
    z-index: 1051 !important;
}

**Comment by Jones-S** [comment]
What was the actual problem behind this?
I don't want to set a random timeout and I don't understand why the .pac-container css rule should resolve the problem (it does not in my case...)
any help very welcome.
