### ISSUE TITLE
Using alternative inputs with the component

### ISSUE THREAD

**Issue by leonardoarroyo** [olefirenko/vue-google-autocomplete#6]
Recently I needed to use vue-google-autocomplete with v-text-field(from vuetify). To do that I needed to fork vue-google-autocomplete and modify the template section.

Do you think it would be within the scope of this lib to accept multiple input fields or a fork would be better?

**Comment by olefirenko** [comment]
I think a fork would be better because what you need is the edge case, so I prefer not include it in the current state. Let me know please about your solution. Curious about your approach.
