### ISSUE TITLE
where in the vue template is there a spot for google api key?

### ISSUE THREAD

**Issue by achillara** [olefirenko/vue-google-autocomplete#60]

**Comment by olefirenko** [comment]
Please check installation section https://github.com/olefirenko/vue-google-autocomplete#installation
You need include API key in `<head>`
```
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY_HERE&libraries=places"></script>
```

**Comment by achillara** [comment]
vue template does not support script src.

**Comment by olefirenko** [comment]
You need to include this script into your application html. Please check the source code of the demo https://olefirenko.github.io/vue-google-autocomplete/

**Comment by achillara** [comment]
<img width="444" alt="screen shot 2018-03-04 at 10 04 04 pm" src="https://user-images.githubusercontent.com/11265448/36955706-0a7ff844-1ff8-11e8-87eb-d568ac0493be.png">

where in this template can I add my google API key? the template does not allow for script src.

**Comment by r4fx** [comment]
here https://github.com/olefirenko/vue-google-autocomplete/blob/master/example/src/index.html

**Comment by Syffs** [comment]
@achillara if you're in a component, set the script (along with your API key) directly in your page or wherever you have access to head. If you don't want to do this, you'll need something like [`vue-meta`](https://github.com/declandewet/vue-meta) to help
