### ISSUE TITLE
Component does not work in a Modal window

### ISSUE THREAD

**Issue by emperorjm** [olefirenko/vue-google-autocomplete#68]
Outside of a modal window this plugin works but inside a bootstrap modal it just does not work.

**Comment by Vlaoff** [comment]
You need to change the z-index of the container
```
.pac-container {
  z-index: 11000 ; /* needs to be > z-index modal */
}
```

**Comment by christine927t** [comment]
> You need to change the z-index of the container
> 
> ```
> .pac-container {
>   z-index: 11000 ; /* needs to be > z-index modal */
> }
> ```

5 years later this helped me :)
