### ISSUE TITLE
Module build failed: Error: Couldn't find preset "es2015" relative to directory

### ISSUE THREAD

**Issue by codelabstudios** [olefirenko/vue-google-autocomplete#7]

**Comment by codelabstudios** [comment]
I removed the following files and compile workred.

/vue-google/autocomplete/webpack.config.js
/vue-google/autocomplete/webpack.mix.js

I'm guessing laravel mix picks up those config. They don't need to be there right?

**Comment by codelabstudios** [comment]
Just had to run 

npm install babel-preset-es2015 --save

**Comment by yannbertrand** [comment]
Why isn't it in the package.json?
