### ISSUE TITLE
handlers[i].call is not a function?

### ISSUE THREAD

**Issue by at-phuongdo** [olefirenko/vue-google-autocomplete#73]
[Vue warn]: Error in mounted hook: "TypeError: handlers[i].call is not a function"
How can I solve it?

**Comment by oschwartz** [comment]
+1

**Comment by haohaoo** [comment]
Check the page life cycle hook function,whether there is an empty life cycle function or some other JS grammer problems in this life cycle function.

**Comment by bigbug-gg** [comment]
What i can do.+1

**Comment by bigbug-gg** [comment]
'create' : [Vue warn]: Error in mounted hook: "TypeError: handlers[i].call is not a function",
 So we must use 'creates'

**Comment by praine** [comment]
I just had the same error - it was because I had "mounted:" rather than "mounted:function():"
