### ISSUE TITLE
How to use in nuxtjs?

### ISSUE THREAD

**Issue by Nisthar** [olefirenko/vue-google-autocomplete#76]
I am getting an error `render function or template not defined in the component` 

I am not sure if this is the actual error. Because nuxt 1.4.0 throws this error most of the time without showing the actual error. I am not able to get this working in nuxtjs.

**Comment by Nisthar** [comment]
I can create a custom component using code from this package and it works fine.

**Comment by Chathula** [comment]
create a file inside plugins folder and put this code.. (here i use filename `map-places.js'`)

```js
import Vue from 'vue';

if (process.BROWSER_BUILD) {
    const VueGoogleAutocomplete = require('vue-google-autocomplete');
    Vue.component('vue-google-autocomplete', VueGoogleAutocomplete);
}

```

then add that file into nuxt.config.js plugin property.

```js
  plugins: [
    '~/plugins/map-places.js',
  ],
```

now you can use this inside a component or page without any issue!

**Comment by kaboume** [comment]
Hi,
I'm using VueGoogleAutocomplete  with Nuxt and everithing works fine with nuxt in mode 'spa'. However, when i set the mode to 'universal' , it doesn't work.

If I write this code in the plugin file  :

```
`import Vue from 'vue';
import VueGoogleAutocomplete from 'vue-google-autocomplete';
Vue.use( VueGoogleAutocomplete );

Vue.component('vue-google-autocomplete', VueGoogleAutocomplete)`
```
or this code :
```
`import Vue from 'vue';
import VueGoogleAutocomplete from 'vue-google-autocomplete';
Vue.use( VueGoogleAutocomplete );

if (process.BROWSER_BUILD) {
    Vue.component('vue-google-autocomplete', VueGoogleAutocomplete)
}`
```

I have this error : 

> Unexpected token <

My page file :


```
<script>
export default {
  data () {
    return {
      address: ''
    }
  },
  methods: {
    getAddressData (addressData, placeResultData, id) {
      console.log(addressData)
      this.address = addressData;
    },
    handleError (e) {
      console.log(e)
    }
  }
}
</script>
```


Have you got an idea ?
Eric

**Comment by coreycoburn** [comment]
For anyone still having trouble implementing in Nuxt, add it as a plugin as mentioned here https://github.com/olefirenko/vue-google-autocomplete/issues/100#issuecomment-441391416

You do not need to `if (process.BROWSER_BUILD)`...

And sidenote, `process.BROWSER_BUILD` is now `process.browser` as of July 2017
https://nuxtjs.org/guide/release-notes#breaking-changes release v1.0.0-rc3

**Comment by kaboume** [comment]
Sorry, I did not specify that it works well with Nuxt in "spa" mode but not in "universal" mode.
Do you have a solution in the "universal" mode?

**Comment by coreycoburn** [comment]
@kaboume correct. SSR false in nuxt config and it works!

**Comment by sambrezo** [comment]
I had to additionally wrap `vue-google-autocomplete` with [`no-ssr`](https://nuxtjs.org/api/components-no-ssr) in my template.

**Comment by patroclo404** [comment]
Hi guys, where do you define the google key and the google library, I'm having the same error but with the following description `ReferenceError: google is not defined`
