### ISSUE TITLE
Add custom result as last suggestion

### ISSUE THREAD

**Issue by julianfox** [olefirenko/vue-google-autocomplete#8]
It would be nice to add a custom result choice as last suggestion, in case where the API can't found the address.

I still didn't found a proper way to do it, any idea ? If I have a solution is it suitable for a Pull request ?

**Comment by olefirenko** [comment]
I guess we can emit the event in such case if no results were found and then a developer can handle this event depending on the business logic of his application. A PR welcome, of course. Thanks!

**Comment by julianfox** [comment]
I has to display this choice even if the API return a result:
![screen shot 2017-05-07 at 1 05 17 pm](https://cloud.githubusercontent.com/assets/1648714/25778364/e66dd92c-3325-11e7-9ec7-c6264e93b8bd.png)

I finally add the option with a click event directly in the DOM generated by Google, it's not perfect but that do perfectly the job ;-)

**Comment by STsaruk** [comment]
> I has to display this choice even if the API return a result: ![screen shot 2017-05-07 at 1 05 17 pm](https://cloud.githubusercontent.com/assets/1648714/25778364/e66dd92c-3325-11e7-9ec7-c6264e93b8bd.png)
> 
> I finally add the option with a click event directly in the DOM generated by Google, it's not perfect but that do perfectly the job ;-)

Can you share the result of how you did it?
