### ISSUE TITLE
How to clear the vue-google-autocomplete component

### ISSUE THREAD

**Issue by tabet-f** [olefirenko/vue-google-autocomplete#95]
I have everything working but I was wondering how to use the exposed component function clear() to clear the address inside vue-google-autocomplete ?

Thanks

**Comment by tabet-f** [comment]
found it in case somebody else needed to know: this.$refs.autocomplete.clear()

**Comment by demency** [comment]
One way I found to clean the field is:

`this.$refs.address.$refs.autocomplete.value = '';`

**Comment by RafalcJ** [comment]
> One way I found to clean the field is:
> 
> `this.$refs.address.$refs.autocomplete.value = '';`

if you focus field again, then value appear
